-- ======================================================
-- MeetSpace 测试数据脚本
-- 数据库: meetspace_db
-- 说明: 运行前请确保后端已启动过一次（JPA ddl-auto=update 会自动建表）
--       密码均为 BCrypt 加密后的 "password123"
-- ======================================================

USE meetspace_db;

-- ── 1. 清空旧数据（可选，测试环境使用）─────────────────────
SET FOREIGN_KEY_CHECKS = 0;
DELETE FROM activity_participant;
DELETE FROM activity;
DELETE FROM users;
SET FOREIGN_KEY_CHECKS = 1;

-- 重置自增序列（Hibernate sequence_table 方式）
-- 如果使用 hibernate_sequence，执行以下语句重置
-- UPDATE hibernate_sequence SET next_val = 1;

-- ── 2. 插入用户（密码: password123）──────────────────────────
-- BCrypt hash of "password123" (generated by Spring BCryptPasswordEncoder)
INSERT INTO users (id, nickname, username, password, age, gender, email, firstname, lastname) VALUES
(1,  'alice',   'alice',   '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 25, '女', 'alice@example.com',   'Alice',   'Wang'),
(2,  'bob',     'bob',     '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 28, '男', 'bob@example.com',     'Bob',     'Li'),
(3,  'charlie', 'charlie', '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 22, '男', 'charlie@example.com', 'Charlie', 'Zhang'),
(4,  'diana',   'diana',   '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 30, '女', 'diana@example.com',   'Diana',   'Liu'),
(5,  'eric',    'eric',    '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 26, '男', 'eric@example.com',    'Eric',    'Chen'),
(6,  'fiona',   'fiona',   '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 24, '女', 'fiona@example.com',   'Fiona',   'Zhao'),
(7,  'george',  'george',  '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 32, '男', 'george@example.com',  'George',  'Sun'),
(8,  'helen',   'helen',   '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 27, '女', 'helen@example.com',   'Helen',   'Yang'),
(9,  'ivan',    'ivan',    '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 29, '男', 'ivan@example.com',    'Ivan',    'Wu'),
(10, 'julia',   'julia',   '$2a$10$ixEgPEXmvF8c02OljUhhDuKBDXEOm2bSv/ILj/yycfo0hPSvArrDK', 23, '女', 'julia@example.com',   'Julia',   'Xu');

-- ── 3. 插入活动 ────────────────────────────────────────────────
--  status tinyint: 0=READY(报名中), 1=CLOSED(已截止), 2=OVER(已结束), 3=DELETED(已删除)
INSERT INTO activity (id, owner_id, title, description, address, start_time, end_time, signup_deadline, status, image, latitude, longitude) VALUES
-- 报名中的活动（status=0, READY）
(100, 1, '周末徒步探险',
 '组织一次城郊山地徒步，全程约10公里，沿途风景优美，欢迎徒步爱好者参与！',
 '北京市海淀区香山公园入口',
 '2026-04-20 08:00:00', '2026-04-20 17:00:00', '2026-04-18 23:59:00',
 0, NULL, 40.0006, 116.1997),

(101, 2, 'Python 入门工作坊',
 '适合零基础学员，3小时带你从环境搭建到写出第一个小程序，全程实战演练。',
 '上海市徐汇区田林路创客空间',
 '2026-04-19 14:00:00', '2026-04-19 17:00:00', '2026-04-17 23:59:00',
 0, NULL, 31.1853, 121.4226),

(102, 3, '城市读书会（第12期）',
 '本期共读《人类简史》，欢迎所有爱好阅读的朋友加入，分享阅读心得。',
 '广州市天河区珠江新城某书店',
 '2026-04-22 19:00:00', '2026-04-22 21:00:00', '2026-04-21 18:00:00',
 0, NULL, 23.1291, 113.3195),

(103, 4, '摄影技巧分享会',
 '手机摄影 + 单反摄影双赛道，专业摄影师现场指导，带上你的相机和作品来交流吧！',
 '深圳市南山区科技园某展厅',
 '2026-04-25 10:00:00', '2026-04-25 13:00:00', '2026-04-23 23:59:00',
 0, NULL, 22.5431, 113.9341),

(104, 5, '桌游&策略游戏聚会',
 '本次携带狼人杀、卡坦岛、三国杀等多款经典桌游，6人起报即可开始，欢迎新朋友！',
 '成都市武侯区某桌游吧',
 '2026-04-27 15:00:00', '2026-04-27 22:00:00', '2026-04-25 23:59:00',
 0, NULL, 30.5728, 104.0668),

(105, 6, 'Yoga 晨练',
 '户外瑜伽早课，舒展身心，迎接美好一天。初学者友好，请自带瑜伽垫。',
 '杭州市西湖区西湖公园草坪',
 '2026-04-19 07:00:00', '2026-04-19 08:30:00', '2026-04-18 22:00:00',
 0, NULL, 30.2423, 120.1534),

(106, 7, '创业分享沙龙',
 '邀请3位连续创业者分享0到1的经历，Q&A环节欢迎提问，适合在校生和职场新人参与。',
 '北京市朝阳区望京SOHO某会议室',
 '2026-05-03 19:00:00', '2026-05-03 21:30:00', '2026-05-01 23:59:00',
 0, NULL, 39.9908, 116.4897),

-- 已截止报名（status=1, CLOSED）
(107, 8, '街头篮球3v3联赛',
 '非正式街头篮球友谊赛，不限水平，以快乐为主，组好3人队即可报名参赛！',
 '武汉市洪山区光谷篮球场',
 '2026-04-20 16:00:00', '2026-04-20 20:00:00', '2026-04-15 23:59:00',
 1, NULL, 30.5115, 114.4106),

(108, 9, '跳蚤市场 & 手工集市',
 '把家里闲置好物带来淘换，也可以展示自己的手工艺品。摊位免费，先到先得！',
 '南京市鼓楼区颐和路社区广场',
 '2026-04-19 09:00:00', '2026-04-19 16:00:00', '2026-04-14 23:59:00',
 1, NULL, 32.0538, 118.7965),

-- 已结束（status=2, OVER）
(109, 10, '线下前端技术交流会',
 'React 18 新特性 + Vue 3 Composition API 实战，大神现场分享，带笔记本参加更佳。',
 '上海市浦东新区某联合办公空间',
 '2026-04-10 14:00:00', '2026-04-10 17:30:00', '2026-04-08 23:59:00',
 2, NULL, 31.2304, 121.4737),

(110, 1, '春季骑行郊游',
 '骑行距离约40公里，途经郊野公园和油菜花田，快来感受春天吧！',
 '北京市通州区大运河森林公园',
 '2026-04-05 08:00:00', '2026-04-05 15:00:00', '2026-04-03 23:59:00',
 2, NULL, 39.8842, 116.7081),

(111, 2, '电影鉴赏：宫崎骏专题',
 '连续放映《千与千寻》《哈尔的移动城堡》《幽灵公主》，映后导演风格交流讨论。',
 '广州市越秀区某文创园放映厅',
 '2026-04-12 18:00:00', '2026-04-12 23:00:00', '2026-04-10 23:59:00',
 2, NULL, 23.1339, 113.2611),

(112, 3, '烹饪大赛：家常菜挑战',
 '每人现场烹饪一道家常菜，其他参赛者投票评分，最高分获得神秘礼品！',
 '深圳市福田区某料理教室',
 '2026-04-08 14:00:00', '2026-04-08 17:00:00', '2026-04-06 23:59:00',
 2, NULL, 22.5488, 114.0545);

-- ── 4. 插入活动参与记录 ─────────────────────────────────────────
INSERT INTO activity_participant (id, activity_id, participant_id) VALUES
-- alice (1) 参加的活动
(1001, 100, 1),
(1002, 101, 1),
(1003, 109, 1),
(1004, 110, 1),
-- bob (2) 参加的活动
(1005, 100, 2),
(1006, 102, 2),
(1007, 111, 2),
-- charlie (3) 参加的活动
(1008, 103, 3),
(1009, 101, 3),
(1010, 109, 3),
-- diana (4) 参加的活动
(1011, 104, 4),
(1012, 105, 4),
(1013, 112, 4),
-- eric (5) 参加的活动
(1014, 106, 5),
(1015, 107, 5),
(1016, 110, 5),
-- fiona (6) 参加的活动
(1017, 108, 6),
(1018, 100, 6),
-- george (7) 参加的活动
(1019, 101, 7),
(1020, 111, 7),
-- helen (8) 参加的活动
(1021, 102, 8),
(1022, 103, 8),
-- ivan (9) 参加的活动
(1023, 104, 9),
(1024, 112, 9),
-- julia (10) 参加的活动
(1025, 105, 10),
(1026, 106, 10);

-- ── 5. 更新 Hibernate sequence（防止后续插入 id 冲突）──────────
UPDATE users_seq SET next_val = 2000;
UPDATE activity_seq SET next_val = 2000;
UPDATE activity_participant_seq SET next_val = 2000;

SELECT 'Test data inserted successfully!' AS status;
SELECT COUNT(*) AS user_count FROM users;
SELECT COUNT(*) AS activity_count FROM activity;
SELECT COUNT(*) AS participant_count FROM activity_participant;
